openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Log in a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /api/logout:
    post:
      summary: Log out a user
      responses:
        '200':
          description: OK
  /api/trips:
    get:
      summary: Get all trips
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
    post:
      summary: Create a new trip
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
      responses:
        '200':
          description: OK
  /api/trips/{id}:
    get:
      summary: Get a trip by ID
      parameters:
        - name: id
          in: path
          description: ID of the trip to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
    put:
      summary: Update a trip by ID
      parameters:
        - name: id
          in: path
          description: ID of the trip to update
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
      responses:
        '200':
          description: OK
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    Trip:
      type: object
      properties:
        tripId:
          type: string
        tripName:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        period:
          type: string
        city:
          type: string
        description:
          type: string
        budget:
          type: number
        tripMembers:
          type: array
          items:
            $ref: '#/components/schemas/User'
        invitationLink:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        invited:
          type: boolean